# Change these first
owner: felipepita # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: Bug Busters
    url: https://bugbusters.com.br
  - name: MontarSite
    url: https://montarsite.com.br
  - name: Chromatox
    url: https://chromatox.com.br
  - name: CCIH
    url: https://ccih.med.br
  - name: LP - Guarda Bens
    url: https://guardabens-lp1.com.br
    maxResponseTime : 50
    
status-website:
  baseUrl: /upptime
  logoUrl: https://www.ms360.com.br/estrutura/img/logo.png
  name: MS360 - Monitor
  introTitle: "**MS360 Security** Solução de monitoramento."
  introMessage: Página para acompanhar em **real-time** e com abertura de ticket automática.
  navbar:
    - title: Status
      href: /
    - title: Suporte
      href: mailto:suporte@montarsite.com.br

i18n:
  footer: MS360 - Security and Performance
  activeIncidents: Incidentes ativos
  allSystemsOperational: Todos os sistemas estão operando
  incidentDetails: Detalhes do incidentes
  incidentFixed: Corrigido
