# Change these first
owner: felipepita # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: Bug Busters
    url: https://bugbusters.com.br
  - name: MontarSite
    url: https://montarsite.com.br
  - name: Chromatox
    url: https://chromatox.com.br
  - name: CCIH
    url: https://ccih.med.br
  - name: E-fish
    url: https://efish.com.br
    maxResponseTime : 20000
  - name: Aulas Online CCIH
    url: https://aulasonline.ccih.med.br
  - name: JAMAICA MANGUEIRAS
    url: https://jamaicamangueiras.com.br
  - name: SISTEMA LARANJA
    url: http://laranja.app.br/
    maxResponseTime : 10000
  - name: AVC2023
    url: https://avc2023.com.br/
    maxResponseTime : 10000
  - name: COLOPROCTO 2023
    url: https://coloprocto2023.com.br/
    maxResponseTime : 10000
  - name: ECIP 2023
    url: https://www.ecip.com.br/
    maxResponseTime : 10000
  - name: Naville
    url: https://www.naville.com.br/
    maxResponseTime : 10000

status-website:
  baseUrl: /upptime
  logoUrl: https://www.ms360.com.br/estrutura/img/logo.png
  name: MS360 - Monitor
  introTitle: "**MS360 Security** Solução de monitoramento."
  introMessage: Página para acompanhar em **real-time** e com abertura de ticket automática.
  navbar:
    - title: Status
      href: /
    - title: Suporte
      href: mailto:suporte@montarsite.com.br

i18n:
  footer: MS360 - Security and Performance
  activeIncidents: Incidentes ativos
  allSystemsOperational: Todos os sistemas estão operando
  incidentDetails: Detalhes do incidentes
  incidentFixed: Corrigido
